{% set name = "openml" %}
{% set version = "0.14.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openml-{{ version }}.tar.gz
  sha256: cf954bd7918f687c46034f9ca097f9bc9ee5d1cdea0df5a8d627efc96abe127d

build:
  number: 1
  noarch: python
  entry_points:
    - openml=openml.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - liac-arff >=2.4.0
    - minio
    - numpy >=1.6.2,<2
    - pandas >=1.0.0
    - pyarrow
    - python >={{ python_min }}
    - python-dateutil
    - requests
    - scikit-learn >=0.18
    - scipy >=0.13.3
    - xmltodict

test:
  imports:
    - openml
    - openml.datasets
  commands:
    - pip check
    - openml --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://openml.org/
  summary: Python API for OpenML
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/openml/openml-python
  doc_url: https://openml.github.io/openml-python/

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
