{% set name = "openml" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openml-{{ version }}.tar.gz
  sha256: 3e4d1da80e9b38f5e44d93b23aa58726a77b7039a5a0498f86a5231aeee8e4a6

build:
  number: 0
  noarch: python
  entry_points:
    - openml=openml.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0
    - packaging
  run:
    - liac-arff >=2.4.0
    - minio
    - numpy >=1.6.2,<2
    - pandas >=1.0.0
    - pyarrow
    - python >=3.8
    - python-dateutil
    - requests
    - scikit-learn >=0.18
    - scipy >=0.13.3
    - xmltodict
    - tqdm

test:
  imports:
    - openml
  commands:
    - pip check
    - openml --help
  requires:
    - pip

about:
  home: https://openml.org/
  summary: Python API for OpenML
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/openml/openml-python
  doc_url: https://openml.github.io/openml-python/

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
