{% set name = "openml" %}
{% set version = "0.12.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openml-{{ version }}.tar.gz
  sha256: cefb4792ca12ee87ab3acc5e5afb4e9d205c398621e2424f2f5de1564cfee849

build:
  number: 0
  noarch: python
  entry_points:
    - openml=openml.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - liac-arff >=2.4.0
    - minio
    - numpy >=1.6.2
    - pandas >=1.0.0
    - pyarrow
    - python >=3.6
    - python-dateutil
    - requests
    - scikit-learn >=0.18
    - scipy >=0.13.3
    - xmltodict

test:
  imports:
    - openml
    - openml.datasets
  commands:
    - pip check
    - openml --help
  requires:
    - pip

about:
  home: https://openml.org/
  summary: Python API for OpenML
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/openml/openml-python
  doc_url: https://openml.github.io/openml-python/

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
